
export const NIGERIA_STATES = [
  "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", 
  "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", 
  "Federal Capital Territory", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", 
  "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger", 
  "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", 
  "Yobe", "Zamfara"
];

export const NIGERIA_CITIES: Record<string, string[]> = {
  "Lagos": ["Ikeja", "Lagos Island", "Victoria Island", "Ikoyi", "Surulere", "Apapa", "Agege", "Alimosho"],
  "Kano": ["Kano Metropolitan", "Fagge", "Dala", "Gwale", "Tarauni", "Nassarawa", "Ungogo", "Kumbotso"],
  "Ibadan": ["Ibadan North", "Ibadan South-West", "Ibadan North-East", "Ibadan North-West", "Ibadan South-East"],
  "Kaduna": ["Kaduna North", "Kaduna South", "Chikun", "Igabi", "Kajuru"],
  "Port Harcourt": ["Port Harcourt City", "Obio-Akpor", "Eleme", "Okrika", "Ogu–Bolo"],
  "Benin City": ["Oredo", "Egor", "Ikpoba-Okha", "Ovia North-East", "Ovia South-West"],
  "Maiduguri": ["Maiduguri Metropolitan Council", "Jere", "Konduga", "Mafa"],
  "Zaria": ["Zaria City", "Sabon Gari", "Tudun Wada"],
  "Aba": ["Aba North", "Aba South", "Osisioma", "Ugwunagbo"],
  "Jos": ["Jos North", "Jos South", "Jos East", "Bassa"],
  "Ilorin": ["Ilorin West", "Ilorin East", "Ilorin South"],
  "Oyo": ["Oyo West", "Oyo East", "Atiba"],
  "Enugu": ["Enugu North", "Enugu South", "Enugu East"],
  "Abeokuta": ["Abeokuta North", "Abeokuta South", "Odeda", "Ewekoro"],
  "Abuja": ["Abuja Municipal", "Gwagwalada", "Kuje", "Bwari", "Kwali", "Abaji"],
  "Sokoto": ["Sokoto North", "Sokoto South", "Wamako", "Kware"],
  "Onitsha": ["Onitsha North", "Onitsha South", "Ogbaru"],
  "Warri": ["Warri North", "Warri South", "Warri South-West"],
  "Okene": ["Okene", "Adavi"],
  "Calabar": ["Calabar Municipal", "Calabar South"],
  "Uyo": ["Uyo", "Ikono", "Ibesikpo Asutan"],
  "Abakaliki": ["Abakaliki", "Ebonyi", "Ohaukwu"],
  "Bauchi": ["Bauchi", "Toro", "Dass"],
  "Makurdi": ["Makurdi", "Guma", "Gwer West"],
  "Akure": ["Akure North", "Akure South"],
  "Gombe": ["Gombe", "Akko", "Yamaltu/Deba"],
  "Umuahia": ["Umuahia North", "Umuahia South", "Ikwuano"],
  "Yenagoa": ["Yenagoa", "Kolokuma/Opokuma", "Southern Ijaw"],
  "Jalingo": ["Jalingo", "Yorro", "Zing"],
  "Lafia": ["Lafia", "Obi", "Doma"],
  "Ikeja": ["Ikeja", "Agege", "Alimosho"],
  "Owerri": ["Owerri Municipal", "Owerri North", "Owerri West"],
  "Damaturu": ["Damaturu", "Fune", "Gujba"],
  "Gusau": ["Gusau", "Tsafe", "Bungudu"],
  "Birnin Kebbi": ["Birnin Kebbi", "Aleiro", "Arewa Dandi"],
  "Dutse": ["Dutse", "Kiyawa", "Auyo"],
  "Asaba": ["Oshimili South", "Oshimili North", "Aniocha South"],
  "Lokoja": ["Lokoja", "Kogi", "Ajaokuta"],
  "Yola": ["Yola North", "Yola South", "Girei"],
  "Minna": ["Minna", "Chanchaga", "Bosso"],
  "Ado Ekiti": ["Ado Ekiti", "Irepodun/Ifelodun", "Ekiti South-West"],
  "Osogbo": ["Osogbo", "Olorunda", "Irepodun"]
};
