// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { config, validateEnvironment } from '@/config/environment';

// Validate environment before creating client
const validation = validateEnvironment();
if (!validation.isValid) {
  console.error('❌ Supabase client initialization failed:', validation.errors);
  throw new Error(
    `Environment validation failed: ${validation.errors.join(', ')}`
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  config.supabase.url,
  config.supabase.anonKey,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },
    global: {
      headers: {
        'X-Client-Info': `${config.app.name}@${config.app.version}`,
      },
    },
  }
);
