// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caagbqzwkgfhtzyizyzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhYWdicXp3a2dmaHR6eWl6eXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NzM4NzEsImV4cCI6MjA1NjI0OTg3MX0.tGKwRfauviZoFCaf0-QD5T7VWW0cfZsOnwb9qnzIrlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
